<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>453f3bc6-7dd3-4fb2-b428-2c045028beec</UserSecretsId>
	  <ApplicationInsightsResourceId>/subscriptions/979324e5-17ea-450e-bed2-26d05ec4d43e/resourcegroups/appdev-rg-dev-we-travelinspiration/providers/microsoft.insights/components/appdev-appi-dev-we-travelinspiration</ApplicationInsightsResourceId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Automapper" Version="13.0.1" />
		<PackageReference Include="Azure.Data.Tables" Version="12.9.1" />
		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.22.0" />
		<PackageReference Include="Azure.Storage.Files.Shares" Version="12.18.0" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.20.0" /> 
		<PackageReference Include="FluentValidation" Version="11.10.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.2.2" />
		<PackageReference Include="microsoft.entityframeworkcore.sqlserver" Version="10.0.8" />
		<PackageReference Include="microsoft.entityframeworkcore.tools" Version="10.0.8">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.3" />
		<PackageReference Include="Polly" Version="8.4.1" />
	</ItemGroup>

</Project>
